export const apiConstantsURL = {
  authentication: {
    login: `accounts/login/`,
    logout: `accounts/logout/`,
    register: `accounts/register/`,
    verifyOtp: `accounts/verify_otp/`,
    sendOtpForForgotPassword: `accounts/send_otp_password_reset/`,
    resendOtp: `accounts/resend_otp/`,
    resetPassword: `accounts/verify_otp_password_reset/`,
    details: `accounts/details/`,
    notification: `accounts/notifications/`,
    sso: `accounts/sso/`,
  },
  profile: {
    personalInfo: `user_profiles/job_seeker_personal/`,
    generalInfo: `user_profiles/job_seeker_general/`,
    additionalInfo: `user_profiles/job_seeker_additional/`,
    adminMetaDataInfo: `user_profiles/get_admin_meta_details/`,
    // qualifications: `user_profiles/qualifications/`,
    // experience: `user_profiles/experience/`,
    // skillSet: `user_profiles/skill_set/`,
    // certifications: `user_profiles/certifications/`,
    // projects: `user_profiles/projects/`,
    // socialUrls: `user_profiles/social_urls/`,
    uploadDocument: `user_profiles/document/`,
    storeFCMToken: `user_profiles/store_fcm_token/`,
    candidateSearch: `user_profiles/filter_job_seeker`,
    findRecruiter: `user_profiles/list_all_recruiter/`,
    findStudent: `user_profiles/list_all_job_seeker/`,
    deleteJobSeeker: `user_profiles/remove_job_seeker/`,
    deleteRecruiter: `user_profiles/remove_recruiter/`,
    // deleteUser: `accounts/remove_user/`,
    // deletejobseeker: `user_profiles/remove_job_seeker/`,
    companyProfile: `user_profiles/company_profile/`,
    recruiterFounding: `user_profiles/recruiter_founding/`,
    saveCandidate: `accounts/save_candidate/`,
    socialUrlsRecruiter: `user_profiles/social_urls_recruiter/`,
    socialUrlsJobSeeker: `user_profiles/social_urls_job_seeker/`,
    profileImage: `user_profiles/upload_profile_image/`,
    questionImage: `user_profiles/upload_question_image/`,
    updateCandidateStatus: `jobs/application_status/`,
  },
  jobs: {
    jobInfo: `jobs/job_info/`,
    jobList: `jobs/list_jobs/`,
    applyJob: `jobs/apply_job/`,
    submittedJobs: `jobs/list_submitted_jobs/`,
    candidateApplication: `jobs/submitted_jobs_application/`,
    myPostedJobs: `jobs/my_posted_jobs/`,
    saveJobs: `jobs/save_job/`,
    overallJobSeekerRecruiterData: `jobs/summary/`,
    updateJobStatus: `jobs/update_job_status/`,
  },
  communication: {
    chatMessage: `jobs/chat/`,
  },
  createJob: {
    jobDetail: `jobs/job_details/`,
    jobDetailsById: `jobs/`,
  },
  payment: {
    orderId: `payment/create_order/`,
    captureTransaction: `payment/capture_transaction/`,
  },
  assessment: {
    getAllSubjects: `assessment/list_all_subjects/`,
    getSubjectById: `assessment/get_subject_by_id/`,
    updateSubject: `assessment/update_subject/`,
    createSubject: `assessment/create_Subject/`,
    subjectInfo: `assessment/get_subjectInfo/`,
    updateQuestion: `assessment/update_question/`,
    questionInfo: `assessment/get_questionInfo/`,
    deleteSubject: `assessment/delete_subject/`,
    deleteQuestion: `assessment/delete_question/`,
    getQuestionBySubjectId: `assessment/get_question_by_subject_id/`,
    getQuestionById: `assessment/get_question_by_id/`,
  },
};
